# Generated by Django 6.0 on 2025-12-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_completed', models.BooleanField(default=False)),
                ('task_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
